/**
 * AutoERP Shared Types
 *
 * This package contains TypeScript types generated from PHP DTOs.
 * DO NOT manually edit these files - they are auto-generated by:
 *   php artisan typescript:transform
 *
 * See CLAUDE.md Rule #7: Types Flow from Backend
 */

export {};
